spring:
  application:
    name: personagens

  datasource:
    username: aplicacao
    password: teste1234
    url: jdbc:mysql://localhost:3306/personagensDb

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  sql:
    init:
      mode: never
